# Generated by Django 2.2.10 on 2020-03-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200314_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedrroms',
            new_name='bedrooms',
        ),
    ]
